# Generated by Django 6.0.2 on 2026-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=40)),
                ('dep_desc', models.CharField(max_length=40)),
                ('dep_head', models.CharField(max_length=40)),
            ],
        ),
    ]
