# Generated by Django 6.0.2 on 2026-02-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('Code', models.CharField(max_length=20)),
                ('Dept', models.CharField(max_length=20)),
            ],
        ),
    ]
