# Generated by Django 6.0.2 on 2026-02-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=40)),
                ('Emp_id', models.CharField(max_length=40)),
                ('Dep', models.CharField(max_length=40)),
                ('Query', models.CharField(max_length=80)),
                ('Status', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='add_employee',
            old_name='contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='add_employee',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='add_employee',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='add_employee',
            old_name='name',
            new_name='Name',
        ),
    ]
