# Generated by Django 6.0.2 on 2026-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_query_rename_contact_add_employee_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
