# Generated by Django 6.0.2 on 2026-02-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_query_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Dep',
            new_name='Dept',
        ),
    ]
