# Generated by Django 6.0.2 on 2026-02-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_dep_query_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.BooleanField(default='default'),
        ),
    ]
