# Generated by Django 6.0.2 on 2026-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_query_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.BooleanField(default='pending'),
        ),
    ]
