# Generated by Django 6.0.2 on 2026-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_query_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Reply',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.BooleanField(default='pending'),
        ),
    ]
