# Generated by Django 6.0.2 on 2026-03-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_query_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('item_desc', models.CharField(max_length=40)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='image')),
                ('item_color', models.CharField(max_length=20)),
                ('item_category', models.CharField(max_length=40)),
                ('item_quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
