# Generated by Django 6.0.2 on 2026-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('razorpay_id', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
