# Generated by Django 6.0.2 on 2026-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
