# Generated by Django 6.0.2 on 2026-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_order_razorpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='Status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
